### ISSUE TITLE
Fix or ignore all linting issues

### ISSUE THREAD

**Issue by DooomiT** [Jarr0d161/TeamFightChaticts#14]
In order to use pylint in the pipeline the codebase has to be cleaned up once.
Therefore run `pipenv run lint` & fix all upcomming errors.
Docstrings shall be handeled in https://github.com/Jarr0d161/TeamFightChaticts/issues/12.

After this is done, the lint step in our [cicd pipeline](https://github.com/Jarr0d161/TeamFightChaticts/blob/main/.github/workflows/cicd.yaml)  has to be enabled again

**Comment by Bonifatius94** [comment]
Fixed all linter warnings (or disabled the warning)
Docstring warnings are currently disable in .pylintrc
